### ISSUE TITLE
sugarchain?

### ISSUE THREAD

**Issue by cryptozeny** [MaynardMiner/SWARM#191]
![image](https://user-images.githubusercontent.com/37016180/64246160-447a3c80-cf47-11e9-87af-4431c6d45ac4.png)

is this miner support sugarchain?

**Comment by MaynardMiner** [comment]
At one point, I was using the same miner config file for your miner (sugarchain) and jaydee's cpuminer-opt. Which ever one was the latest cpuminer-opt, I would use. It was mainly because I had to compile a generic version every time I had to update it in linux, and was time consuming.

I have since separated the two completely, and now have they have their own versions, however.

**Comment by MaynardMiner** [comment]
![image](https://user-images.githubusercontent.com/38481606/65645644-3e1b3580-dfc6-11e9-9cea-c813ad7e44e4.png)

Your miner btw has been the most profitable for awhile now. SWARM rarely switches off of it for me. Good job!
