### ISSUE TITLE
Add Dual (multiple) CPU Recognition

### ISSUE THREAD

**Issue by SixLitr** [MaynardMiner/SWARM#197]
Unless I missed it, I cannot find any way to enable my mining test rigs that use dual CPU configurations. Probably not as common, but there are some of us miners that use dual-CPU, multi-GPU rig setups. With RandomX and its variants I anticipate this request becoming more common.

Amazing work, super impressed...I just can use it on my dual CPU rigs (If I try to run a second xmrig instance I am unable to because its taken up by SWARM already)

HiveOS miner.

**Comment by MaynardMiner** [comment]
Hmm...

I have never used dual CPU, and I don't own one.

There are two obstacles here-

1.) How to detect there is a second cpu on rig. Both with SWARM's auto-detect, and adding -Type CPU2.
2.) If miners are capable of determining there is a second cpu, and an argument to provide it. I imagine they are, just need to learn how to do so.

Both require some research on my end, I will look into it, but I am interested in adding this. I am just am not familiar.

Also, if you are serious cpu mining on linux (which I assume dual cpu computer is linux), in order to have miners work for all architecture, no matter what rig they are working on- I have provided miners that are generically compiled (march=x86-64). You may want to compile the miners with the march=native flag, so they are optimized for the cpu.

You can use the ``version update`` command to add your own link for the miners if you make yourself a download link.

**Comment by SixLitr** [comment]
Thanks for the assist. I can help if you need to look deeper into dual CPU systems possibly just let me know what you need.

HiveOS recognizes all of them natively or more specifically xmrig, as its the most efficient across the board typically. I have never had to flag any options as the miners auto-detect themselves.

**Comment by MaynardMiner** [comment]
If you are running normal arguments, then it should work in SWARM. You may have to use the ``-CPU_Threads`` argument to set the total number of cores, as I'm not sure SWARM can auto-detect it. If it doesn't work- post the errors or problems, and I can see if I can fix them.

The only issue is, is that HiveOS only affords me 1 slot for a custom miner to set stats.  It may work, but you won't see the miner from the web dashboard, you would have to run commands like ``get stats`` and ``get active`` to see what it is doing.

I have been exploring their API further, to see if I can open custom flight sheets for the miners that are working, so SWARM will send stats through the flight sheet, that way I can have multiple miners stat to HiveOS.

I have been exploring that, but it requires SWARM to basically self-create h-stats.sh, h-manifest.sh, and h-run.sh on demand. Its something I am looking at for SWARM_V2.

**Comment by SixLitr** [comment]
Sounds good, I will tinker with it some more on my end. Any major feature/enhancements would best be applied to v2 of SWARM, just maintain v1 and I will patiently wait. Thanks again!
