### ISSUE TITLE
Profits not work in SWARM.3.0.5.linux! Nothing to mine ...

### ISSUE THREAD

**Issue by vvpospelo** [MaynardMiner/SWARM#315]
Profits not work in SWARM.3.0.5.linux! Nothing to mine ...

My config on HiveOS:
-Poolname nicehash,zergpool,zpool -Donate .5 -Location EUROPE -API_Key XXX -Type NVIDIA1 -kwh 0.0519 -WattOMeter Yes -Wallet1 %WAL% -Nicehash_Wallet1 XXX -PasswordCurrency1 BTC -RigName1 %WORKER_NAME% -Currency USD -CoinExchange BTC -Historical_Bias 9:2 -Throttle 0 -Switch_Threshold 3 -Nicehash_Fee 2 -Stat_Algo 4_Hour_EMA -Stat_Coin 4_Hour_EMA -Update Yes -Benchmark 4 -Interval 5 -StatsInterval 3 -Time_Wait 10 -SWARM_Mode No -Conserve Yes -Rejections 12 -Timeout 12 -Bans beamv2:bminer-1,mtp

[stats.txt](https://github.com/MaynardMiner/SWARM/files/4310839/stats.txt)

**Comment by incodemines** [comment]
There was a typo in the change log/update notes regarding `-Stat_Algo` and `-Stat_Coin` and the parameters that resulted in profits showing as $0.00 or even negative values. I believe that was isolated to only being associated with `1_Hour_MA` and `1_Hour_EMA` which has since been updated here: https://github.com/MaynardMiner/SWARM/wiki/beta2-changes

It's possible that it also effects `4_Hour_MA` and `4_Hour_EMA` but I'm sure Maynard can confirm soon. You may need to run the command `clear_profits` when SWARM is not in the middle of looping stats or building the stat database to see if that clears it up but I suspect it has something to do with the `-Stat_Algo` and `-Stat_Coin` arguments. I use `Hour_EMA` for both arguments and can confirm it works.

**Comment by MaynardMiner** [comment]
Yeah, my dummy self totally forgot to update the wiki on the release. I changed it last minute. I actually changed it one spot in the wiki article, but not the other.

``4_Hour_EMA`` and ``4_Hour_MA`` should be:

``Hour_4_EMA`` and ``Hour_4_MA``

I have updated the wiki to reflect that change.

```
10_Minute_MA
10_Minutes_EMA
15_Minute_MA
15_Minute_EMA
30_Minute_MA
30_Minute_EMA
Hour_MA
Hour_EMA
Hour_4_MA
Hour_4_EMA
Day_MA
Day_EMA
```

**Comment by MaynardMiner** [comment]
Run ``clear_profits`` after changing, to ensure that the zero values doesn't affect moving averages

**Comment by vvpospelo** [comment]
> Запустите `clear_profits`после изменения, чтобы убедиться, что нулевые значения не влияют на скользящие средние.

no 'Live' mode too ?

**Comment by MaynardMiner** [comment]
Live still exists
