### ISSUE TITLE
miniz-1 Has Failed To Download

### ISSUE THREAD

**Issue by vvpospelo** [MaynardMiner/SWARM#316]
miniz-1 Has Failed To Download

**Comment by MaynardMiner** [comment]
I saw this myself.

Miniz is leaving some weird file in its old folder that will not let powershell delete it. I opened with ``nautilus`` and the file was listed as 'unknown encryption'....Powershells ``remove-item`` says it can't delete it due to unknown attributes of that file.

Manually delete miniz-1 from bin folder, and then retry. It should succeed.

**Comment by MaynardMiner** [comment]
This is a bug with .NET (powershell), not SWARM.

If it continues to happen as miniz puts out releases, I will using linux ``rm`` command instead. It may be specific to previous release, as there was no issues prior.

**Comment by MaynardMiner** [comment]
Reopening issue so I can attempt to address it
