### ISSUE TITLE
Implement native miner logs under the /bin/minername/log folder

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#412]
Please implement native miner logs under the /bin/minername/logs folder, to aid with troubleshooting of past events in HiveOS. Example below shows banned events. These are logged in NVIDIA1/AMD1 logs, but erased at next miner switch.. Previous logs are therefore purged, with no way to find root cause of previous failures. 

![image](https://user-images.githubusercontent.com/99490445/197345462-afab505e-466d-4fc7-b28a-46cf34c04c24.png)

This exists by default in naitve HiveOS out of the box. I know this is possible as I see native nanominer logs in the folders below, probably triggered by custom miner arguments I used during testing ...

![image](https://user-images.githubusercontent.com/99490445/197345350-ba7840d1-53d4-490f-a4e7-72b66d65f095.png)

Alternatively, this could be implemented by maintaining a history of time-stamped NVIDIA1/AMD1 logs, rather than just the single active NVIDIA1/AMD1 log file... 

This may or may not be related/associated to incident " Better Logging #395" ...

**Comment by MaynardMiner** [comment]
I'm going to close this. It is #395. I promise by end of week I will have a new logging method. It's just not a small change.

On windows side, there is no way to record screen output easily. Some miners have anti-debugging and it triggers them trying to capture output. That's why I run `-log` arguments in lieu of just capturing ``gnu screen`` output like HiveOS does.

And if I use minerlog_2022-10-21...etc. the miner will parse the -10 as a argument.

It's all so very dumb and complicated because each miner works differently. I'm trying to come up with a solution.
