### ISSUE TITLE
HIVEOS displays double the Hash Rate from SWARM

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#433]
HIVEOS displays double the Hash Rate from SWARM

![image](https://user-images.githubusercontent.com/99490445/198891142-a9dc4558-1c49-4459-902c-dc76a2431905.png)

![image](https://user-images.githubusercontent.com/99490445/198891188-b0a1ced3-e2bb-4cd4-9ffa-0a0b1faa89e4.png)

**Comment by MaynardMiner** [comment]
Okay will check api

**Comment by MaynardMiner** [comment]
srbmulti api just add the total of the threads together. I dunno why it would be wrong. But since I changed it to hash/s instead of khs as the default hashrate, I can use the same stat that SWARM is using for its hashrate instead of trying to add the hashrate of each individual gpu. I will implement this next release.
