### ISSUE TITLE
Support for PimpOS

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#59]
I have purchased a copy of PimpOS. I haven't had a chance to use, but I plan to test and fix whatever needed to support soon.

Once confirmed it can be ran without issue, I will help with integrating swarm api in linux methods for stats.

**Comment by ParaplegicRacehorse** [comment]
Have you checked with the PimpOS team? They are very responsive with requests and may help with integration (I make no promises on their behalf. They were very helpful in getting my ARMv6 dust miners configured for miner.farm; just my experience) since this is a feature they are missing in their miner.farm product and OS. Ask. The worst that can happen is they say No.

**Comment by MaynardMiner** [comment]
I have talked with Melt in the past, and he follows the project. He is indeed a cool guy.

It's not really an issue of integration, it wouldn't take long to do, and I imagine would be easy, since their is a tcp for stats that are near the same as eth miner:

https://github.com/MaynardMiner/SWARM/blob/master/help/TCP_API.txt

#1 issue with SWARM project is when I make support for something, and then a small change to env in the platform question breaks it. I am monitoring 5 frameworks on 5 different rigs now for changes.  I can set it up, if I know there are active users that will support beta testing/monitoring, and notify me of issues/compatibility. If I know there are going to be active users, then I will plug it into PimpOS ( I already have a copy), make sure it will start, and then pass it on to PimpOS for them to add to their miner list.

This post is more for individuals/users to let me know that they want to see PimpOS and SWARM. I can do what is needed on my end to make it happen if there were people interested.
